services:
  - type: web
    name: tolotanana-backend
    env: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm run prisma:migrate:deploy && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tolotanana-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
